export const shoes = [
  {
    id: '1',
    name: 'Greenwood',
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ['Teal', 'Yellow', 'Pink'],
    price: '150',
    image: '/greenwood.jpg',
    alttext:
      'a pair of low heeled yellow shoes with blue cutouts on the side and toe box',
    desc: 'low heel, leather sole, leather upper',
  },
  {
    id: '2',
    name: 'Seneca',
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ['Teal', 'Yellow', 'Pink'],
    price: '150',
    image: '/seneca.jpg',
    alttext: 'a pair of and cream shoes high heeled shoes in sandal style',
    desc: 'mid heel, leather sole, leather upper',
  },
  {
    id: '3',
    name: 'Newport',
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ['Teal', 'Yellow', 'Pink'],
    price: '150',
    image: '/newport.jpg',
    alttext: 'a pair of blue high heeled suede shoes with buckle',
    desc: 'mid heel, leather sole, leather upper',
  },
  {
    id: '4',
    name: 'Eldorado',
    sizes: [39, 40, 41, 42, 43, 44, 45, 46],
    colors: ['Teal', 'Yellow', 'Pink'],
    price: '150',
    image: '/eldorado.jpg',
    alttext: 'a pair of burgundy lace up boots',
    desc: 'Flat boot, leather sole, leather upper',
  },
];
